apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  labels:
    app: playground-inception
spec:
  description: Our ArgoCD Project to deploy our app locally
  sourceRepos:
    - "https://github.com/msabwat/playground-inception.git"
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-inception-app
spec:
  project: development
  source:
    repoURL: https://github.com/msabwat/playground-inception.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

